tasks:
  - name: Init
    init: |
      npm install
      npm run clone-repos
      gp sync-done init
    command: |
      code -add /workspace/*
      exit

  - name: foo
    init: |
      gp sync-await init
      cd /workspace/foo
      echo 'cd into the repo's directory and then run init commands'
    command: |
      cd /workspace/foo
      echo 'cd into the repo's directory and then run init commands'

  - name: some
    init: |
      gp sync-await init
      cd /workspace/some-api
      echo 'cd into the repo's directory and then run init commands'
    command: |
      cd /workspace/some-api
      echo 'cd into the repo's directory and then run init commands'
